[package]
name = "hp_pp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
membarrier = { git = "https://github.com/jeehoonkang/membarrier-rs.git", branch = "pebr" }
crossbeam-utils = "0.8.14"
